config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'setup', to: 'setup#new', as: 'setup'
  post 'setup', to: 'setup#create'

  namespace :users do
    resource :profile, only: %i[show edit update]
  end

  resources :users do
    member do
      get :collection
    end
  end

  resources :user_comicbooks, only: %i[create destroy]

  resources :series do
    resources :comicbooks
  end
end

app/models/comicbook.rb
# frozen_string_literal: true

# A Comic Book
class Comicbook < ApplicationRecord
  has_many :user_comicbooks, dependent: :destroy
  has_many :users, through: :user_comicbooks

  has_one_attached :cover_image

  belongs_to :series

  enum format: { issue: 0, volume: 1 }

  validates :entity_number, :format, presence: true
end

app/controllers/comicbooks_controller.rb
# frozen_string_literal: true

# Comicbooks controller
class ComicbooksController < ApplicationController
  before_action :set_comicbook, only: %i[show edit update destroy]
  before_action :set_series
  before_action :set_user, only: %i[show edit update destroy]

  def show
    @series      = @comic.series
    @user_comics = @user.comicbooks.pluck(:id)
  end

  def new
    @comic = @series.comicbooks.build
    authorize @comic
  end

  def edit
    authorize @comic
    @series = @comic.series
  end

  def create
    @comic  = @series.comicbooks.build(comicbook_params)

    authorize @comic

    if @comic.save
      redirect_to @series, notice: I18n.t('notices.comicbook_created')
    else
      render :new
    end
  end

  def update
    authorize @comic

    if @comic.update(comicbook_params)
      redirect_to series_comicbook_path(@series, @comic), notice: I18n.t('notices.comicbook_updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @comic

    @series = @comic.series
    redirect_to @series, notice: I18n.t('notices.comicbook_deleted') if @comic.destroy
  end

  private

  def set_comicbook
    @comic = Comicbook.find_by(id: params[:id])

    return if @comic

    redirect_to series_index_url, alert: I18n.t('alerts.comicbook_not_found')
  end

  def set_series
    @series = Series.find_by(id: params[:series_id])
  end

  def set_user
    @user = current_user
  end

  def comicbook_params
    params.require(:comicbook).permit(:title, :format, :entity_number, :cover_price, :cover_date, :synopsis,
                                      :cover_image)
  end
end

app/views/comicbooks/edit.html.erb
<%= render 'comicbooks/partials/navtabs' %>

<h2 class="h3">General</h2>

<ul class="list-group mb-4">
  <li class="list-group-item">
    <%= form_with(model: [@series, @comic], local: true) do |form| %>
      <% if @comic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

          <ul>
          <% @comic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <% if @comic.cover_image.attached? %>
          <%= image_tag @comic.cover_image, height: "260" %>
        <% else %>
          <%= image_tag 'no_photo_available.svg', height: "260" %>
        <% end %>
      </div>

      <div class="mb-3">
        <%= form.label :cover_image, class: "form-label" %>
        <%= form.file_field :cover_image, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :format, class: "form-label" %>
        <%= form.collection_select :format, Comicbook.formats.keys, :to_s, :humanize, {}, { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= form.label :entity_number, class: "form-label" %>
        <%= form.text_field :entity_number, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :cover_price, class: "form-label" %>
        <%= form.text_field :cover_price, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :cover_date, class: "form-label" %>
        <%= form.date_field :cover_date, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :synopsis, class: "form-label" %>
        <%= form.text_area :synopsis, class: "form-control" %>
      </div>

      <div class="d-flex">
        <%= link_to "Cancel", series_comicbook_path(@series, @comic), class: "btn btn-outline-secondary me-2", role: "button" %>
        <div class="actions">
          <%= form.submit "Update", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </li>
</ul>

<h2 class="h3">Danger Zone</h2>

<ul class="list-group mb-4">
  <li class="list-group-item border-danger d-flex justify-content-between align-items-center">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Delete this comic</div>
      Once you delete a comicbook, there is no going back. Please be certain.
    </div>
    <div class="flex-md-order-1 flex-order-2">
      <%= button_to "Delete Comic", series_comicbook_path(@series, @comic),
                    method: :delete,
                    data: { turbo_confirm: "Are you sure you want to delete this comic?" },
                    class: "btn btn-danger", role: "button" %>
    </div>
  </li>
</ul>

app/views/comicbooks/new.html.erb
<h2><%= "#{@series.name} - New Comic" %></h2>

<%= form_with(model: [@series, @comic], local: true) do |form| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
        <% @comic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :format, class: "form-label" %>
    <%= form.collection_select :format, Comicbook.formats.keys, :to_s, :humanize, {}, { class: "form-control" } %>
  </div>

  <div class="mb-3">
    <%= form.label :entity_number, class: "form-label" %>
    <%= form.text_field :entity_number, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cover_price, class: "form-label" %>
    <%= form.text_field :cover_price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cover_date, class: "form-label" %>
    <%= form.date_field :cover_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :synopsis, class: "form-label" %>
    <%= form.text_area :synopsis, class: "form-control" %>
  </div>

  <div class="d-flex">
    <%= link_to "Cancel", series_path(@series), class: "btn btn-outline-secondary me-2", role: "button" %>
    <div class="actions">
      <%= form.submit "Create", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/comicbooks/show.html.erb
<%= render 'comicbooks/partials/navtabs' %>

<div class="row">
  <div class="col-lg-8">
    <h2><%= "#{@comic.series.name} ##{@comic.entity_number}" %></h2>

    <% if @user_comics.include?(@comic.id) %>
      <%= form_with url: user_comicbook_path(@user, @comic), method: :delete, local: true do %>
        <%= hidden_field_tag :user_id, @user.id %>
        <%= hidden_field_tag :comic_id, @comic.id %>
        <%= button_tag type: "submit", class: "btn btn-light btn-sm" do %>
          <%= image_tag 'icons/circle-plus-fill.svg', height: "20" %> Collected
        <% end %>
      <% end %>
    <% else %>
      <%= form_with url: user_comicbooks_path, method: :post, local: true do %>
        <%= hidden_field_tag :user_id, @user.id %>
        <%= hidden_field_tag :comic_id, @comic.id %>
        <%= button_tag type: "submit", class: "btn btn-light btn-sm" do %>
          <%= image_tag 'icons/circle-plus-nofill.svg', height: "20" %> Collect
        <% end %>
      <% end %>
    <% end %>

    <hr />

    <% if @comic.title %>
      <h3><%= @comic.title %></h3>
    <% end %>

    <p><%= @comic.synopsis %></p>

    <h3>Cover Price</h3>
    <% if @comic.cover_price && @comic.cover_price != "" %>
      <p>$<%= @comic.cover_price %></p>
    <% else %>
      <p>Unknown</p>
    <% end %>

    <h3>Cover Date</h3>
    <% if @comic.cover_date %>
      <p><%= @comic.cover_date.strftime("%B %Y") %></p>
    <% else %>
      <p>Unknown</p>
    <% end %>
  </div>

  <div class="col-lg-4">
    <% if @comic.cover_image.attached? %>
      <%= image_tag @comic.cover_image, class: "img-fluid", style: "width: 100%;" %>
    <% else %>
      <%= image_tag 'no_photo_available.svg', alt: 'Image of generic comic book cover', width: '100%', height: '100%' %>
    <% end %>
    <%= link_to "Back to Series", series_path(@series), class: "btn btn-primary", role: "button" %>
  </div>
</div>