config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'setup', to: 'setup#new', as: 'setup'
  post 'setup', to: 'setup#create'

  namespace :users do
    resource :profile, only: %i[show edit update]
  end

  resources :users do
    member do
      get :collection
    end
  end

  resources :user_comicbooks, only: %i[create destroy]

  resources :series do
    resources :comicbooks
  end
end

app/controllers/setup_controller.rb
# frozen_string_literal: true

# First-time Setup Controller
class SetupController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :redirect_if_users_exist

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = true

    if @user.save
      sign_in(@user) # Automatically sign in the new admin user
      redirect_to root_path, notice: I18n.t('notices.admin_user_created')
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end

  def redirect_if_users_exist
    redirect_to root_path if User.exists?
  end
end

app/views/setup/new.html.erb
<%= render 'setup/partials/modal' %>

<div class="d-flex justify-content-center align-items-center">
  <div class="col-md-4">
    <h2 class="d-flex justify-content-center align-items-center">Create Admin User</h2>
    <div class="d-flex justify-content-center align-items-center">
      <%= image_tag "logo.svg", alt: "Comicdex logo", height: "100" %>
    </div>
    <%= form_with(model: @user, url: setup_path, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-floating">
        <%= f.email_field :email, autocomplete: "email", class: "form-control", id: "floatingEmail", placeholder: "name@example.com" %>
        <%= f.label :email, for: "floatingEmail" %>
      </div>

      <div class="form-floating">
        <%= f.text_field :nickname, autocomplete: "nickname", class: "form-control", id: "floatingNickname", placeholder: "nickname" %>
        <%= f.label :nickname, for: "floatingNickname" %>
      </div>

      <div class="my-3">
        <div class="form-floating">
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control", id: "floatingPassword", placeholder: "password" %>
          <%= f.label :password, for: "floatingPassword" %>
        </div>

        <div class="form-floating">
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", id: "floatingConfirmPassword", placeholder: "password" %>
          <%= f.label :password_confirmation, for: "floatingConfirmPassword" %>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Create Admin", class: "btn btn-primary w-100 py-2" %>
      </div>
    <% end %>
  </div>
</div>