config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'static_pages#home'

  get 'setup', to: 'setup#new', as: 'setup'
  post 'setup', to: 'setup#create'

  namespace :users do
    resource :profile, only: %i[show edit update]
  end

  resources :users do
    member do
      get :collection
    end
  end

  resources :user_comicbooks, only: %i[create destroy]

  resources :series do
    resources :comicbooks
  end
end

app/controllers/series_controller.rb
# frozen_string_literal: true

# Series controller
class SeriesController < ApplicationController
  before_action :set_series, only: %i[show edit update destroy]
  before_action :set_user, only: %i[index show edit update destroy]

  def index
    @all_series = Series.all
  end

  def show
    @comics      = @series.comicbooks
    @user_comics = @user.comicbooks.where(series: @series)
  end

  def new
    @series = Series.new
    authorize @series
  end

  def edit
    authorize @series
  end

  def create
    @series = Series.new(series_params)
    authorize @series

    if @series.save
      redirect_to @series, notice: I18n.t('notices.series_created')
    else
      render :new
    end
  end

  def update
    authorize @series

    if @series.update(series_params)
      redirect_to @series, notice: I18n.t('notices.series_updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @series

    @series.destroy
    redirect_to series_index_url, notice: I18n.t('notices.series_deleted')
  end

  private

  def set_series
    @series = Series.find_by(id: params[:id])

    return if @series

    redirect_to series_index_url, alert: I18n.t('alerts.series_not_found')
  end

  def set_user
    @user = current_user
  end

  def series_params
    params.require(:series).permit(:name, :start_date, :end_date, :language, :synopsis, :series_image)
  end
end

app/views/series/edit.html.erb
<%= render 'series/partials/navtabs' %>

<h2 class="h3">General</h2>

<ul class="list-group mb-4">
  <li class="list-group-item">
    <%= form_with(model: @series, local: true) do |form| %>
      <% if @series.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

          <ul>
          <% @series.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <% if @series.series_image.attached? %>
          <%= image_tag @series.series_image, height: "260" %>
        <% else %>
          <%= image_tag 'no_photo_available.svg', height: "260" %>
        <% end %>
      </div>

      <div class="mb-3">
        <%= form.label :series_image, class: "form-label" %>
        <%= form.file_field :series_image, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :start_date, class: "form-label" %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :end_date, class: "form-label" %>
        <%= form.date_field :end_date, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :language, class: "form-label" %>
        <%= form.text_field :language, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :synopsis, class: "form-label" %>
        <%= form.text_area :synopsis, class: "form-control" %>
      </div>

      <div class="d-flex">
        <%= link_to "Cancel", series_path(@series), class: "btn btn-outline-secondary me-2", role: "button" %>
        <div class="actions">
          <%= form.submit "Update", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </li>
</ul>

<h2 class="h3">Danger Zone</h2>

<ul class="list-group mb-4">
  <li class="list-group-item border-danger d-flex justify-content-between align-items-center">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Delete this series</div>
      Once you delete a series, there is no going back. Please be certain.
    </div>
    <div class="flex-md-order-1 flex-order-2">
      <%= button_to "Delete Series", series_path(@series),
                    method: :delete,
                    data: { turbo_confirm: "Are you sure you want to delete this series?" },
                    class: "btn btn-danger", role: "button" %>
    </div>
  </li>
</ul>

app/views/series/index.html.erb
<h2>Comics by Series</h2>

<p>
  Here you can browse all the comicbooks in the database by series. In the future, you will be able to search and filter
  on various comicbook attributes.  Stay tuned!
</p>

<% if @user.admin? %>
  <div class="d-flex">
    <%= link_to "Add +", new_series_path, class: "btn btn-success", role: "button" %>
  </div>
<% end %>

<hr />

<div class="row">
  <% if @all_series.any? %>
    <% @all_series.each do |series| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 mb-4">
        <%= link_to series_path(series), class: 'text-decoration-none' do %>
          <div class="card">
            <div style="height: 240px; overflow: hidden; display: flex; justify-content: center; align-items: start;">
              <% if series.series_image.attached? %>
                <%= image_tag series.series_image, class: "card-img-top", style: "max-width: 100%; width: auto; height: auto;" %>
              <% else %>
                <%= image_tag 'no_photo_available.svg', class: "card-img-top" %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title text-truncate"><%= "#{series.name}" %></h5>
              <h6><%= "#{series.start_date.strftime("%Y")}" %></h6>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>There are no comicbook series to show :(</p>
  <% end %>
</div>

app/views/series/new.html.erb
<h2>New Comic Series</h2>

<%= form_with(model: @series, local: true) do |form| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% @series.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :start_date, class: "form-label" %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :end_date, class: "form-label" %>
    <%= form.date_field :end_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :language, class: "form-label" %>
    <%= form.text_field :language, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :synopsis, class: "form-label" %>
    <%= form.text_area :synopsis, class: "form-control" %>
  </div>

  <div class="d-flex">
    <%= link_to "Cancel", series_index_path, class: "btn btn-outline-secondary me-2", role: "button" %>
    <div class="actions">
      <%= form.submit "Create", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/series/show.html.erb
<%= render 'series/partials/navtabs' %>

<h2><%= @series.name %> (Series)</h2>

<% if @series.synopsis %>
  <p><%= @series.synopsis %></p>
<% end %>

<% if @user.admin? %>
  <div class="d-flex">
    <%= link_to "Add +", new_series_comicbook_path(@series.id), class: "btn btn-success", role: "button" %>
  </div>
<% end %>

<hr />

<div class="row">
  <% if @comics.any? %>
    <% @comics.each do |comic| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 mb-4">
        <%= link_to series_comicbook_path(@series, comic), class: "text-decoration-none" do %>
          <div class="card">
            <div style="height: 240px; overflow: hidden;">
              <% if comic.cover_image.attached? %>
                <%= image_tag comic.cover_image, class: "card-img-top", style: "max-width: 100%; width: auto; height: auto;" %>
              <% else %>
                <%= image_tag 'no_photo_available.svg', class: "card-img-top" %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <% if comic.format == "issue" %>
                  <%= "#{@series.name} ##{comic.entity_number}" %>
                <% else %>
                  <%= "#{@series.name} vol. #{comic.entity_number}" %>
                <% end %>
              </h5>
              <% if @user_comics.include?(comic) %>
                <p class="text-success">Collected</p>
              <% else %>
                <p class="text-danger">Not Collected</p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>No comics in this series.</p>
  <% end %>
</div>